// Pure TypeScript export utility — no React imports.
// All component files should import from here to trigger Excel downloads.
import * as XLSXLib from "xlsx";

// ─── Public types ────────────────────────────────────────────────────────────

export interface ColumnConfig {
  key: string;
  header: string;
  width?: number; // character width hint; clamped to [12, 50]
}

export interface SheetConfig {
  name: string;
  data: Record<string, unknown>[];
  columns?: ColumnConfig[];
  isSummary?: boolean;
}

export interface ExportOptions {
  filename: string;
  sheets: SheetConfig[];
  filters?: Record<string, string>;
  dateRange?: string;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

/**
 * Returns a human-readable filter string:
 *   "Region: North | Status: Active"
 * Skips entries whose value is empty / "All" / "all".
 */
export function formatFiltersForExport(
  filters: Record<string, string>,
): string {
  const parts = Object.entries(filters)
    .filter(
      ([, v]) =>
        v !== "" && v.toLowerCase() !== "all" && v.toLowerCase() !== "none",
    )
    .map(([k, v]) => `${k}: ${v}`);
  return parts.length > 0 ? parts.join(" | ") : "None";
}

/**
 * Builds a sanitised filename for an export, e.g.:
 *   buildFilename("Feedback", { CES: "Negative" }, "Apr2026")
 *   → "Feedback_NegativeCES_Apr2026.xlsx"
 */
export function buildFilename(
  module: string,
  filters?: Record<string, string>,
  dateStr?: string,
): string {
  const parts: string[] = [module];

  if (filters) {
    const significant = Object.entries(filters).filter(
      ([, v]) =>
        v !== "" && v.toLowerCase() !== "all" && v.toLowerCase() !== "none",
    );
    for (const [k, v] of significant) {
      // Combine value + key, e.g. "Negative" + "CES" → "NegativeCES"
      const segment = `${v}${k}`.replace(/[^a-zA-Z0-9]/g, "");
      if (segment) parts.push(segment);
    }
  }

  if (dateStr) {
    parts.push(dateStr.replace(/[^a-zA-Z0-9]/g, ""));
  }

  const base = parts.join("_").replace(/_{2,}/g, "_");
  return `${base}.xlsx`;
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

function formatDateNow(): string {
  const d = new Date();
  const dd = String(d.getDate()).padStart(2, "0");
  const mm = String(d.getMonth() + 1).padStart(2, "0");
  const yyyy = d.getFullYear();
  const hh = String(d.getHours()).padStart(2, "0");
  const min = String(d.getMinutes()).padStart(2, "0");
  return `${dd}/${mm}/${yyyy} ${hh}:${min}`;
}

/**
 * Derive column widths from data + header length.
 * Clamps each col to [minWidth, maxWidth].
 */
function computeColWidths(
  headers: string[],
  rows: string[][],
  minWidth = 12,
  maxWidth = 50,
): XLSXLib.ColInfo[] {
  return headers.map((header, colIdx) => {
    const headerLen = header.length;
    const dataMax = rows.reduce((acc, row) => {
      const cell = row[colIdx] ?? "";
      return Math.max(acc, String(cell).length);
    }, 0);
    const raw = Math.max(headerLen, dataMax) + 2; // +2 padding
    return { wch: Math.min(maxWidth, Math.max(minWidth, raw)) };
  });
}

function buildSummarySheet(
  options: ExportOptions,
  totalRecords: number,
): XLSXLib.WorkSheet {
  const rows: (string | number)[][] = [
    ["EXPORT SUMMARY"],
    [],
    ["Export Date", formatDateNow()],
    [
      "Filters Applied",
      options.filters ? formatFiltersForExport(options.filters) : "None",
    ],
  ];

  if (options.dateRange) {
    rows.push(["Date Range", options.dateRange]);
  }

  rows.push(["Total Records", totalRecords]);
  rows.push([]);
  rows.push(["Generated by", "Frootle India Pvt.Ltd. — Performance Hub"]);

  const ws = XLSXLib.utils.aoa_to_sheet(rows);

  // Style the title cell (A1) — bold via cell comment metadata is limited in
  // the open-source xlsx build; set column widths instead.
  ws["!cols"] = [{ wch: 22 }, { wch: 60 }];

  return ws;
}

function buildDataSheet(config: SheetConfig): XLSXLib.WorkSheet {
  const { data, columns } = config;

  if (data.length === 0) {
    // Return an empty sheet with headers only
    const headers = columns?.map((c) => c.header) ?? [];
    const ws = XLSXLib.utils.aoa_to_sheet([
      headers.length > 0 ? headers : ["No data available"],
    ]);
    ws["!cols"] = headers.map((h) => ({ wch: Math.max(12, h.length + 2) }));
    return ws;
  }

  let headers: string[];
  let rows: string[][];

  if (columns && columns.length > 0) {
    // Respect caller-provided column order and display names
    headers = columns.map((c) => c.header);
    rows = data.map((record) =>
      columns.map((c) => {
        const val = record[c.key];
        return val === null || val === undefined ? "" : String(val);
      }),
    );
  } else {
    // Auto-derive from first record
    const keys = Object.keys(data[0]);
    headers = keys;
    rows = data.map((record) =>
      keys.map((k) => {
        const val = record[k];
        return val === null || val === undefined ? "" : String(val);
      }),
    );
  }

  const aoa: string[][] = [headers, ...rows];
  const ws = XLSXLib.utils.aoa_to_sheet(aoa);
  ws["!cols"] = computeColWidths(headers, rows);

  // Apply caller-specified widths where provided (overrides auto-size)
  if (columns) {
    columns.forEach((col, idx) => {
      if (col.width !== undefined && ws["!cols"]) {
        ws["!cols"][idx] = {
          wch: Math.min(50, Math.max(12, col.width)),
        };
      }
    });
  }

  return ws;
}

// ─── Main export function ─────────────────────────────────────────────────────

/**
 * Creates and triggers a browser download of an Excel (.xlsx) file.
 *
 * A "Summary" sheet is always prepended (unless the caller already includes
 * one with `isSummary: true`).
 */
export function exportToExcel(options: ExportOptions): void {
  const wb = XLSXLib.utils.book_new();

  // Determine total records from the first non-summary data sheet
  const firstDataSheet = options.sheets.find((s) => !s.isSummary);
  const totalRecords = firstDataSheet?.data.length ?? 0;

  // Check if caller already provided a summary sheet
  const hasSummary = options.sheets.some((s) => s.isSummary);

  if (!hasSummary) {
    const summaryWs = buildSummarySheet(options, totalRecords);
    XLSXLib.utils.book_append_sheet(wb, summaryWs, "Summary");
  }

  for (const sheetConfig of options.sheets) {
    const ws = sheetConfig.isSummary
      ? buildSummarySheet(options, totalRecords)
      : buildDataSheet(sheetConfig);

    // Sanitise sheet name — Excel allows max 31 chars, no special chars
    const safeName = sheetConfig.name.replace(/[/\\?*[\]:]/g, "-").slice(0, 31);

    XLSXLib.utils.book_append_sheet(wb, ws, safeName);
  }

  XLSXLib.writeFile(wb, options.filename);
}
