/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SWOT {
    weaknesses: Array<string>;
    strengths: Array<string>;
    traits: Array<string>;
    threats: Array<string>;
    opportunities: Array<string>;
    cesScore: number;
    problems: Array<string>;
    feedbacks: Array<string>;
    fiplCode: string;
}
export interface BatchResult {
    errors: Array<string>;
    successCount: bigint;
    failCount: bigint;
}
export interface Attendance {
    date: string;
    recordId: bigint;
    labType: Variant_eod_daysBrief_attendance;
    fiplCode: string;
    reason: string;
    daysOff: bigint;
}
export interface Performance {
    videoCallDemos: bigint;
    operationalDiscipline: number;
    softSkillsScore: number;
    productKnowledgeScore: number;
    salesInfluenceIndex: number;
    reviewCount: bigint;
    complaintVisits: bigint;
    demoVisits: bigint;
    fiplCode: string;
}
export interface TopPerformer {
    accessories: bigint;
    name: string;
    rank: bigint;
    totalSales: number;
    extendedWarranty: bigint;
    fiplCode: string;
}
export interface SalesRecord {
    saleType: Variant_accessories_extendedWarranty;
    recordId: bigint;
    quantity: bigint;
    brand: Variant_tineco_ecovacs_coway_kuvings_instant;
    amount: number;
    product: string;
    saleDate: string;
    fiplCode: string;
}
export interface Employee {
    region: string;
    status: Variant_active_onHold;
    joinDate: string;
    name: string;
    role: string;
    fseCategory: string;
    avatarUrl: string;
    department: string;
    familyDetails: string;
    pastExperience: string;
    fiplCode: string;
}
export interface FeedbackEntry {
    remark: string;
    customerName: string;
    contact: string;
    agent: string;
    callDate: string;
    entryId: bigint;
    cesScore: number;
    brand: Variant_tineco_ecovacs_coway_kuvings_instant;
    product: string;
    fiplCode: string;
}
export interface DashboardStats {
    totalEmployees: bigint;
    totalSalesAmount: number;
    activeCount: bigint;
    averageCesScore: number;
}
export enum Order {
    less = "less",
    equal = "equal",
    greater = "greater"
}
export enum Variant_accessories_extendedWarranty {
    accessories = "accessories",
    extendedWarranty = "extendedWarranty"
}
export enum Variant_active_onHold {
    active = "active",
    onHold = "onHold"
}
export enum Variant_eod_daysBrief_attendance {
    eod = "eod",
    daysBrief = "daysBrief",
    attendance = "attendance"
}
export enum Variant_tineco_ecovacs_coway_kuvings_instant {
    tineco = "tineco",
    ecovacs = "ecovacs",
    coway = "coway",
    kuvings = "kuvings",
    instant = "instant"
}
export interface backendInterface {
    addAttendance(record: Attendance): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addEmployee(employee: Employee): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addFeedback(entry: FeedbackEntry): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addSalesRecord(record: SalesRecord): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    batchAttendanceUpload(records: Array<Attendance>): Promise<BatchResult>;
    batchEmployeeUpload(records: Array<Employee>): Promise<BatchResult>;
    batchFeedbackUpload(records: Array<FeedbackEntry>): Promise<BatchResult>;
    batchParametersUpload(records: Array<Performance>): Promise<BatchResult>;
    batchSWOTUpload(records: Array<SWOT>): Promise<BatchResult>;
    batchSalesUpload(records: Array<SalesRecord>): Promise<BatchResult>;
    batchTopPerformersUpload(records: Array<TopPerformer>): Promise<BatchResult>;
    /**
     * / Clear the entire key-value store.
     */
    clearAllKV(): Promise<void>;
    compareTopPerformersBySales(a: TopPerformer, b: TopPerformer): Promise<Order>;
    /**
     * / Delete only attendance records
     */
    deleteAllAttendance(): Promise<void>;
    /**
     * / Delete all data (employees, sales, attendance, SWOT, performance, feedback, top performers)
     */
    deleteAllData(): Promise<void>;
    /**
     * / DELETE OPERATIONS
     * / Delete all employees and all related data.
     */
    deleteAllEmployees(): Promise<void>;
    /**
     * / Delete only feedback/calling records
     */
    deleteAllFeedback(): Promise<void>;
    /**
     * / Delete only performance/parameters records
     */
    deleteAllPerformances(): Promise<void>;
    /**
     * / Delete only SWOT records
     */
    deleteAllSWOT(): Promise<void>;
    /**
     * / Delete only sales records
     */
    deleteAllSales(): Promise<void>;
    /**
     * / Delete only top performer records
     */
    deleteAllTopPerformers(): Promise<void>;
    deleteEmployee(fiplCode: string): Promise<void>;
    /**
     * / Delete a key from the store.
     */
    deleteKV(key: string): Promise<void>;
    getActiveEmployees(): Promise<Array<Employee>>;
    getAllEmployees(): Promise<Array<Employee>>;
    /**
     * / Get all key-value pairs as an array of (key, value) tuples.
     */
    getAllKV(): Promise<Array<[string, string]>>;
    getAllPerformancesSortedBySII(): Promise<Array<Performance>>;
    getAttendanceByFIPL(fiplCode: string): Promise<Array<Attendance>>;
    getDashboardStats(): Promise<DashboardStats>;
    getEmployee(fiplCode: string): Promise<Employee | null>;
    getFeedbackByFIPL(fiplCode: string): Promise<Array<FeedbackEntry>>;
    /**
     * / Get a value by key. Returns null if not found.
     */
    getKV(key: string): Promise<string | null>;
    getPerformanceByFIPL(fiplCode: string): Promise<Performance | null>;
    getSWOTByFIPL(fiplCode: string): Promise<SWOT | null>;
    getSalesByFIPL(fiplCode: string): Promise<Array<SalesRecord>>;
    getTopPerformers(): Promise<Array<TopPerformer>>;
    /**
     * / Set a key-value pair in the store.
     */
    setKV(key: string, value: string): Promise<void>;
    updateEmployee(employee: Employee): Promise<void>;
    upsertPerformance(performance: Performance): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    upsertSWOT(swot: SWOT): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { Attendance as _Attendance, Employee as _Employee, FeedbackEntry as _FeedbackEntry, Order as _Order, Performance as _Performance, SWOT as _SWOT, SalesRecord as _SalesRecord } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAttendance(arg0: Attendance): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addAttendance(to_candid_Attendance_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAttendance(to_candid_Attendance_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async addEmployee(arg0: Employee): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addEmployee(to_candid_Employee_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEmployee(to_candid_Employee_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async addFeedback(arg0: FeedbackEntry): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addFeedback(to_candid_FeedbackEntry_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFeedback(to_candid_FeedbackEntry_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async addSalesRecord(arg0: SalesRecord): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addSalesRecord(to_candid_SalesRecord_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSalesRecord(to_candid_SalesRecord_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async batchAttendanceUpload(arg0: Array<Attendance>): Promise<BatchResult> {
        if (this.processError) {
            try {
                const result = await this.actor.batchAttendanceUpload(to_candid_vec_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.batchAttendanceUpload(to_candid_vec_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async batchEmployeeUpload(arg0: Array<Employee>): Promise<BatchResult> {
        if (this.processError) {
            try {
                const result = await this.actor.batchEmployeeUpload(to_candid_vec_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.batchEmployeeUpload(to_candid_vec_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async batchFeedbackUpload(arg0: Array<FeedbackEntry>): Promise<BatchResult> {
        if (this.processError) {
            try {
                const result = await this.actor.batchFeedbackUpload(to_candid_vec_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.batchFeedbackUpload(to_candid_vec_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async batchParametersUpload(arg0: Array<Performance>): Promise<BatchResult> {
        if (this.processError) {
            try {
                const result = await this.actor.batchParametersUpload(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.batchParametersUpload(arg0);
            return result;
        }
    }
    async batchSWOTUpload(arg0: Array<SWOT>): Promise<BatchResult> {
        if (this.processError) {
            try {
                const result = await this.actor.batchSWOTUpload(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.batchSWOTUpload(arg0);
            return result;
        }
    }
    async batchSalesUpload(arg0: Array<SalesRecord>): Promise<BatchResult> {
        if (this.processError) {
            try {
                const result = await this.actor.batchSalesUpload(to_candid_vec_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.batchSalesUpload(to_candid_vec_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async batchTopPerformersUpload(arg0: Array<TopPerformer>): Promise<BatchResult> {
        if (this.processError) {
            try {
                const result = await this.actor.batchTopPerformersUpload(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.batchTopPerformersUpload(arg0);
            return result;
        }
    }
    async clearAllKV(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllKV();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllKV();
            return result;
        }
    }
    async compareTopPerformersBySales(arg0: TopPerformer, arg1: TopPerformer): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.compareTopPerformersBySales(arg0, arg1);
                return from_candid_Order_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.compareTopPerformersBySales(arg0, arg1);
            return from_candid_Order_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAllAttendance(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllAttendance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllAttendance();
            return result;
        }
    }
    async deleteAllData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllData();
            return result;
        }
    }
    async deleteAllEmployees(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllEmployees();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllEmployees();
            return result;
        }
    }
    async deleteAllFeedback(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllFeedback();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllFeedback();
            return result;
        }
    }
    async deleteAllPerformances(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllPerformances();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllPerformances();
            return result;
        }
    }
    async deleteAllSWOT(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllSWOT();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllSWOT();
            return result;
        }
    }
    async deleteAllSales(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllSales();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllSales();
            return result;
        }
    }
    async deleteAllTopPerformers(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllTopPerformers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllTopPerformers();
            return result;
        }
    }
    async deleteEmployee(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEmployee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEmployee(arg0);
            return result;
        }
    }
    async deleteKV(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteKV(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteKV(arg0);
            return result;
        }
    }
    async getActiveEmployees(): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveEmployees();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveEmployees();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEmployees(): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmployees();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmployees();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllKV(): Promise<Array<[string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllKV();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllKV();
            return result;
        }
    }
    async getAllPerformancesSortedBySII(): Promise<Array<Performance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPerformancesSortedBySII();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPerformancesSortedBySII();
            return result;
        }
    }
    async getAttendanceByFIPL(arg0: string): Promise<Array<Attendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceByFIPL(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceByFIPL(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getEmployee(arg0: string): Promise<Employee | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployee(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployee(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeedbackByFIPL(arg0: string): Promise<Array<FeedbackEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedbackByFIPL(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedbackByFIPL(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getKV(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getKV(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKV(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPerformanceByFIPL(arg0: string): Promise<Performance | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPerformanceByFIPL(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPerformanceByFIPL(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSWOTByFIPL(arg0: string): Promise<SWOT | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSWOTByFIPL(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSWOTByFIPL(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSalesByFIPL(arg0: string): Promise<Array<SalesRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesByFIPL(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesByFIPL(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopPerformers(): Promise<Array<TopPerformer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopPerformers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopPerformers();
            return result;
        }
    }
    async setKV(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setKV(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setKV(arg0, arg1);
            return result;
        }
    }
    async updateEmployee(arg0: Employee): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployee(to_candid_Employee_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployee(to_candid_Employee_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async upsertPerformance(arg0: Performance): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertPerformance(arg0);
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertPerformance(arg0);
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async upsertSWOT(arg0: SWOT): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertSWOT(arg0);
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertSWOT(arg0);
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Attendance_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Attendance): Attendance {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Employee_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Employee): Employee {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_FeedbackEntry_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeedbackEntry): FeedbackEntry {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_SalesRecord_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SalesRecord): SalesRecord {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Employee]): Employee | null {
    return value.length === 0 ? null : from_candid_Employee_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Performance]): Performance | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SWOT]): SWOT | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    region: string;
    status: {
        active: null;
    } | {
        onHold: null;
    };
    joinDate: string;
    name: string;
    role: string;
    fseCategory: string;
    avatarUrl: string;
    department: string;
    familyDetails: string;
    pastExperience: string;
    fiplCode: string;
}): {
    region: string;
    status: Variant_active_onHold;
    joinDate: string;
    name: string;
    role: string;
    fseCategory: string;
    avatarUrl: string;
    department: string;
    familyDetails: string;
    pastExperience: string;
    fiplCode: string;
} {
    return {
        region: value.region,
        status: from_candid_variant_n23(_uploadFile, _downloadFile, value.status),
        joinDate: value.joinDate,
        name: value.name,
        role: value.role,
        fseCategory: value.fseCategory,
        avatarUrl: value.avatarUrl,
        department: value.department,
        familyDetails: value.familyDetails,
        pastExperience: value.pastExperience,
        fiplCode: value.fiplCode
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    recordId: bigint;
    labType: {
        eod: null;
    } | {
        daysBrief: null;
    } | {
        attendance: null;
    };
    fiplCode: string;
    reason: string;
    daysOff: bigint;
}): {
    date: string;
    recordId: bigint;
    labType: Variant_eod_daysBrief_attendance;
    fiplCode: string;
    reason: string;
    daysOff: bigint;
} {
    return {
        date: value.date,
        recordId: value.recordId,
        labType: from_candid_variant_n27(_uploadFile, _downloadFile, value.labType),
        fiplCode: value.fiplCode,
        reason: value.reason,
        daysOff: value.daysOff
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    remark: string;
    customerName: string;
    contact: string;
    agent: string;
    callDate: string;
    entryId: bigint;
    cesScore: number;
    brand: {
        tineco: null;
    } | {
        ecovacs: null;
    } | {
        coway: null;
    } | {
        kuvings: null;
    } | {
        instant: null;
    };
    product: string;
    fiplCode: string;
}): {
    remark: string;
    customerName: string;
    contact: string;
    agent: string;
    callDate: string;
    entryId: bigint;
    cesScore: number;
    brand: Variant_tineco_ecovacs_coway_kuvings_instant;
    product: string;
    fiplCode: string;
} {
    return {
        remark: value.remark,
        customerName: value.customerName,
        contact: value.contact,
        agent: value.agent,
        callDate: value.callDate,
        entryId: value.entryId,
        cesScore: value.cesScore,
        brand: from_candid_variant_n32(_uploadFile, _downloadFile, value.brand),
        product: value.product,
        fiplCode: value.fiplCode
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    saleType: {
        accessories: null;
    } | {
        extendedWarranty: null;
    };
    recordId: bigint;
    quantity: bigint;
    brand: {
        tineco: null;
    } | {
        ecovacs: null;
    } | {
        coway: null;
    } | {
        kuvings: null;
    } | {
        instant: null;
    };
    amount: number;
    product: string;
    saleDate: string;
    fiplCode: string;
}): {
    saleType: Variant_accessories_extendedWarranty;
    recordId: bigint;
    quantity: bigint;
    brand: Variant_tineco_ecovacs_coway_kuvings_instant;
    amount: number;
    product: string;
    saleDate: string;
    fiplCode: string;
} {
    return {
        saleType: from_candid_variant_n39(_uploadFile, _downloadFile, value.saleType),
        recordId: value.recordId,
        quantity: value.quantity,
        brand: from_candid_variant_n32(_uploadFile, _downloadFile, value.brand),
        amount: value.amount,
        product: value.product,
        saleDate: value.saleDate,
        fiplCode: value.fiplCode
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    less: null;
} | {
    equal: null;
} | {
    greater: null;
}): Order {
    return "less" in value ? Order.less : "equal" in value ? Order.equal : "greater" in value ? Order.greater : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    onHold: null;
}): Variant_active_onHold {
    return "active" in value ? Variant_active_onHold.active : "onHold" in value ? Variant_active_onHold.onHold : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    eod: null;
} | {
    daysBrief: null;
} | {
    attendance: null;
}): Variant_eod_daysBrief_attendance {
    return "eod" in value ? Variant_eod_daysBrief_attendance.eod : "daysBrief" in value ? Variant_eod_daysBrief_attendance.daysBrief : "attendance" in value ? Variant_eod_daysBrief_attendance.attendance : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tineco: null;
} | {
    ecovacs: null;
} | {
    coway: null;
} | {
    kuvings: null;
} | {
    instant: null;
}): Variant_tineco_ecovacs_coway_kuvings_instant {
    return "tineco" in value ? Variant_tineco_ecovacs_coway_kuvings_instant.tineco : "ecovacs" in value ? Variant_tineco_ecovacs_coway_kuvings_instant.ecovacs : "coway" in value ? Variant_tineco_ecovacs_coway_kuvings_instant.coway : "kuvings" in value ? Variant_tineco_ecovacs_coway_kuvings_instant.kuvings : "instant" in value ? Variant_tineco_ecovacs_coway_kuvings_instant.instant : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    accessories: null;
} | {
    extendedWarranty: null;
}): Variant_accessories_extendedWarranty {
    return "accessories" in value ? Variant_accessories_extendedWarranty.accessories : "extendedWarranty" in value ? Variant_accessories_extendedWarranty.extendedWarranty : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Employee>): Array<Employee> {
    return value.map((x)=>from_candid_Employee_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Attendance>): Array<Attendance> {
    return value.map((x)=>from_candid_Attendance_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeedbackEntry>): Array<FeedbackEntry> {
    return value.map((x)=>from_candid_FeedbackEntry_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SalesRecord>): Array<SalesRecord> {
    return value.map((x)=>from_candid_SalesRecord_n37(_uploadFile, _downloadFile, x));
}
function to_candid_Attendance_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Attendance): _Attendance {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Employee_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Employee): _Employee {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_FeedbackEntry_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeedbackEntry): _FeedbackEntry {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_SalesRecord_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SalesRecord): _SalesRecord {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    saleType: Variant_accessories_extendedWarranty;
    recordId: bigint;
    quantity: bigint;
    brand: Variant_tineco_ecovacs_coway_kuvings_instant;
    amount: number;
    product: string;
    saleDate: string;
    fiplCode: string;
}): {
    saleType: {
        accessories: null;
    } | {
        extendedWarranty: null;
    };
    recordId: bigint;
    quantity: bigint;
    brand: {
        tineco: null;
    } | {
        ecovacs: null;
    } | {
        coway: null;
    } | {
        kuvings: null;
    } | {
        instant: null;
    };
    amount: number;
    product: string;
    saleDate: string;
    fiplCode: string;
} {
    return {
        saleType: to_candid_variant_n13(_uploadFile, _downloadFile, value.saleType),
        recordId: value.recordId,
        quantity: value.quantity,
        brand: to_candid_variant_n10(_uploadFile, _downloadFile, value.brand),
        amount: value.amount,
        product: value.product,
        saleDate: value.saleDate,
        fiplCode: value.fiplCode
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    recordId: bigint;
    labType: Variant_eod_daysBrief_attendance;
    fiplCode: string;
    reason: string;
    daysOff: bigint;
}): {
    date: string;
    recordId: bigint;
    labType: {
        eod: null;
    } | {
        daysBrief: null;
    } | {
        attendance: null;
    };
    fiplCode: string;
    reason: string;
    daysOff: bigint;
} {
    return {
        date: value.date,
        recordId: value.recordId,
        labType: to_candid_variant_n3(_uploadFile, _downloadFile, value.labType),
        fiplCode: value.fiplCode,
        reason: value.reason,
        daysOff: value.daysOff
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    region: string;
    status: Variant_active_onHold;
    joinDate: string;
    name: string;
    role: string;
    fseCategory: string;
    avatarUrl: string;
    department: string;
    familyDetails: string;
    pastExperience: string;
    fiplCode: string;
}): {
    region: string;
    status: {
        active: null;
    } | {
        onHold: null;
    };
    joinDate: string;
    name: string;
    role: string;
    fseCategory: string;
    avatarUrl: string;
    department: string;
    familyDetails: string;
    pastExperience: string;
    fiplCode: string;
} {
    return {
        region: value.region,
        status: to_candid_variant_n7(_uploadFile, _downloadFile, value.status),
        joinDate: value.joinDate,
        name: value.name,
        role: value.role,
        fseCategory: value.fseCategory,
        avatarUrl: value.avatarUrl,
        department: value.department,
        familyDetails: value.familyDetails,
        pastExperience: value.pastExperience,
        fiplCode: value.fiplCode
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    remark: string;
    customerName: string;
    contact: string;
    agent: string;
    callDate: string;
    entryId: bigint;
    cesScore: number;
    brand: Variant_tineco_ecovacs_coway_kuvings_instant;
    product: string;
    fiplCode: string;
}): {
    remark: string;
    customerName: string;
    contact: string;
    agent: string;
    callDate: string;
    entryId: bigint;
    cesScore: number;
    brand: {
        tineco: null;
    } | {
        ecovacs: null;
    } | {
        coway: null;
    } | {
        kuvings: null;
    } | {
        instant: null;
    };
    product: string;
    fiplCode: string;
} {
    return {
        remark: value.remark,
        customerName: value.customerName,
        contact: value.contact,
        agent: value.agent,
        callDate: value.callDate,
        entryId: value.entryId,
        cesScore: value.cesScore,
        brand: to_candid_variant_n10(_uploadFile, _downloadFile, value.brand),
        product: value.product,
        fiplCode: value.fiplCode
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_tineco_ecovacs_coway_kuvings_instant): {
    tineco: null;
} | {
    ecovacs: null;
} | {
    coway: null;
} | {
    kuvings: null;
} | {
    instant: null;
} {
    return value == Variant_tineco_ecovacs_coway_kuvings_instant.tineco ? {
        tineco: null
    } : value == Variant_tineco_ecovacs_coway_kuvings_instant.ecovacs ? {
        ecovacs: null
    } : value == Variant_tineco_ecovacs_coway_kuvings_instant.coway ? {
        coway: null
    } : value == Variant_tineco_ecovacs_coway_kuvings_instant.kuvings ? {
        kuvings: null
    } : value == Variant_tineco_ecovacs_coway_kuvings_instant.instant ? {
        instant: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_accessories_extendedWarranty): {
    accessories: null;
} | {
    extendedWarranty: null;
} {
    return value == Variant_accessories_extendedWarranty.accessories ? {
        accessories: null
    } : value == Variant_accessories_extendedWarranty.extendedWarranty ? {
        extendedWarranty: null
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_eod_daysBrief_attendance): {
    eod: null;
} | {
    daysBrief: null;
} | {
    attendance: null;
} {
    return value == Variant_eod_daysBrief_attendance.eod ? {
        eod: null
    } : value == Variant_eod_daysBrief_attendance.daysBrief ? {
        daysBrief: null
    } : value == Variant_eod_daysBrief_attendance.attendance ? {
        attendance: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_active_onHold): {
    active: null;
} | {
    onHold: null;
} {
    return value == Variant_active_onHold.active ? {
        active: null
    } : value == Variant_active_onHold.onHold ? {
        onHold: null
    } : value;
}
function to_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Attendance>): Array<_Attendance> {
    return value.map((x)=>to_candid_Attendance_n1(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Employee>): Array<_Employee> {
    return value.map((x)=>to_candid_Employee_n5(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<FeedbackEntry>): Array<_FeedbackEntry> {
    return value.map((x)=>to_candid_FeedbackEntry_n8(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<SalesRecord>): Array<_SalesRecord> {
    return value.map((x)=>to_candid_SalesRecord_n11(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
